# Original variant:
#   https://github.com/kivy/kivent/blob/2.2-release/.travis.yml
language: python
python:
  - "2.7"

sudo: required
dist: trusty

before_install:
  - sudo apt-get update -qq
  ## https://kivy.org/docs/installation/installation.html#development-version
  - sudo apt-get install -qq gstreamer0.10-plugins-good libgl1-mesa-dev libgles2-mesa-dev zlib1g-dev
  - sudo apt-get build-dep -qq python-pygame python-gst0.10 python-dev python-enchant
  - sudo apt-get install -qq build-essential python-pygame python-gst0.10 python-dev python-enchant
  ## Kivy Package Dependencies
  ##   https://kivy.org/docs/installation/installation.html#ubuntu
  - pip install --upgrade pip wheel setuptools pyopengl pyenchant
  - pip install Cython
  - pip install --upgrade Cython==0.25.2
  - pip install -r ./requirements.txt

# Run test
script:
  - python -m pytest tests

virtualenv:
    system_site_packages: true