# Original variant:
#   https://github.com/kivy/kivent/blob/2.2-release/.travis.yml
language: python
python:
  - 2.7

sudo: required
dist: trusty

before_install:
  - yes | sudo add-apt-repository ppa:mc3man/trusty-media
  - sudo apt-get update
  - sudo apt-get install build-essential ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
  - sudo apt-get install libmtdev1
  - pip install -U pip
  - pip install Cython
  - pip install -r ./requirements.txt

# Run test
script:
  - python -m pytest tests/test_edit_plan.py
  - python -m pytest tests/test_simple.py
